import { createContext, useContext, useState, useCallback } from "react";

const LanguageContext = createContext(null);

export const LANGUAGES = [
  { code: "en", label: "English" },
  { code: "rw", label: "Kiny" },
  { code: "fr", label: "French" },
];

const TRANSLATIONS = {
  en: {
    // Nav Sections
    main_menu: "Main Menu",
    management: "Management",
    finance: "Finance",
    reports: "Reports",
    others: "Others",
    production_nav: "Production",
    production: "Production",
    real_estate: "Real Estate",
    supply_chain: "Supply Chain",
    operations: "Operations",

    // Nav Items
    dashboard: "Dashboard",
    stock: "SITOKE",
    sales: "Sales",
    retail_sales: "Retail Sales",
    wholesale_orders: "Wholesale Orders",
    procurement: "Procurement",
    workers: "Workers",
    customers: "Customers",
    suppliers: "Suppliers",
    invoices: "Invoices",
    expenses: "Expenses",
    profit_loss: "Profit & Loss",
    financial_books: "Financial Books",
    financial_books_sub: "Auto-generated journal, ledger, cash book & trial balance",
    sales_report: "Sales Report",
    stock_report: "Stock Report",
    worker_performance: "Worker Performance",
    audit_log: "Audit Log",
    notifications: "Notifications",
    settings: "Settings",
    raw_materials: "Raw Materials",
    finished_goods: "Finished Goods",
    production_runs: "Production Runs",
    properties: "Properties",
    tenants: "Tenants",
    rent_payments: "Rent Payments",
    maintenance: "Maintenance",
    debt_management: "Debt Management",
    receivables: "Owed to Us",
    due_date: "Due Date",
    debtor: "Debtor",
    creditor: "Creditor",
    pay_debt: "Record Payment",
    add_debt: "Add Debt",
    total_debt: "Total Debt",
    overdue: "Overdue",

    // Businesses
    industry: "INZIRA INSIGHTS",
    shop: "INZIRA INSIGHTS",
    real_estate_biz: "INZIRA INSIGHTS",
    switch_business: "Switch Business",

    // Auth
    welcome_back: "Welcome back",
    sign_in_account: "Sign in to your account",
    email: "Email address",
    password: "Password",
    remember_me: "Remember me",
    sign_in: "Sign In",
    signing_in: "Signing in...",
    login_failed: "Login failed. Check your credentials.",

    // General Actions
    save: "Save",
    cancel: "Cancel",
    delete: "Delete",
    edit: "Edit",
    add: "Add",
    search: "Search",
    loading: "Loading...",
    actions: "Actions",
    view: "View",
    print: "Print",
    export: "Export",
    filter: "Filter",
    clear: "Clear",
    all: "All",
    status: "Status",
    date: "Date",
    total: "Total",
    amount: "Amount",
    name: "Name",
    phone: "Phone",
    category: "Category",
    description: "Description",
    success: "Success",
    error: "Error",
    confirm_delete: "Are you sure you want to delete this?",

    // Dashboard
    total_revenue: "Total Revenue",
    total_sales: "Total Sales",
    stock_value: "Stock Value",
    active_workers: "Active Workers",
    recent_activity: "Recent Activity",
    top_selling_items: "Top Selling Items",
    sales_trend: "Sales Trend",
    low_stock_alerts: "Low Stock Alerts",
    items_sold: "items sold",

    // Stock & Production
    add_item: "Add Item",
    item_name: "Item Name",
    barcode: "Barcode",
    quantity: "Quantity",
    cost_price: "Cost Price",
    selling_price: "Selling Price",
    min_stock: "Min Stock",
    size: "Size",
    color: "Color",
    in_stock: "In Stock",
    low_stock: "Low Stock",
    out_of_stock: "Out of Stock",
    transfer_stock: "Transfer Stock",
    planned: "Planned",
    in_progress: "In Progress",
    completed: "Completed",
    cancelled: "Cancelled",

    // Sales & Rent
    new_sale: "New Sale",
    invoice_no: "Invoice No",
    customer: "Customer",
    payment_method: "Payment Method",
    subtotal: "Subtotal",
    tax: "Tax",
    grand_total: "Grand Total",
    void_sale: "Void Sale",
    sale_details: "Sale Details",
    cash: "Cash",
    momo: "Mobile Money",
    bank: "Bank Transfer",

    // Real Estate
    occupied: "Occupied",
    vacant: "Vacant",
    partial: "Partial",
    address: "Address",
    address_label: "Address",
    rent_status: "Rent Status",
    paid: "Paid",
    pending: "Pending",

    // Finance
    revenue: "Revenue",
    cogs: "COGS (Cost of Goods)",
    gross_profit: "Gross Profit",
    net_profit: "Net Profit",
    operating_expenses: "Operating Expenses",
    monthly_summary: "Monthly Summary",

    // Settings
    business_info: "Business Information",
    shop_name: "Shop Name",
    city: "City",
    currency: "Currency",
    language: "Language",
    roles_permissions: "Roles & Permissions",

    // Nav sections
    nav_main: "Main",
    nav_inventory: "Inventory",
    nav_crm: "CRM",
    nav_finance: "Finance",
    nav_reports: "Reports",
    nav_intelligence: "Intelligence",
    nav_admin: "Admin",
    nav_lender: "Lender",

    // Nav items (missing)
    point_of_sale: "Point of Sale",
    sales_history: "Sales History",
    purchase_orders: "Purchase Orders",
    payables: "Payables",
    tax_reports: "Tax Reports",
    health_score: "Health Score",
    pulse_admin: "Pulse Admin",
    portfolio: "Portfolio",

    // Dashboard strings
    dashboard_subtitle: "Here's your business snapshot for today",
    revenue_today: "Revenue Today",
    net_cash_today: "Net Cash Today",
    monthly_revenue: "Monthly Revenue",
    monthly_profit: "Monthly Profit",
    business_health_score: "Business Health Score",
    health_score_subtitle: "Calculated from your data",
    sales_trend_7day: "7-Day Sales Trend",
    no_sales_data: "No sales data yet — make your first sale to see the trend",
    all_stock_ok: "✓ All stock levels OK",
    get_advisory_help: "Get advisory help",
    no_score_yet: "No score yet — add sales and expenses to get scored",
    add_expense: "Add Expense",
    receive_stock: "Receive Stock",
    transactions: "transactions",
    items_need_attention: "items need attention",
    view_all_stock: "View all stock →",
    no_recent_activity: "No recent activity",
    sales_minus_expenses: "Sales minus expenses",
    revenue_minus_cogs: "Revenue minus expenses & COGS",
    vs_last_month: "vs last month",
    out_of_100: "out of 100",

    // NewSale
    point_of_sale_subtitle: "Record a new sale",
    search_by_name_or_barcode: "Search by name or barcode…",
    current_sale: "Current Sale",
    cart_empty: "Cart is empty",
    customer_name_optional: "Customer name (optional)",
    complete_sale: "Complete Sale",
    no_products_match: "No products match your search",
    out_label: "OUT",
    left_in_stock: "left",
    confirm_sale: "Confirm Sale",
    walk_in: "Walk-in",
    payment_label: "Payment",
    record_sale: "Record Sale",
    partial_payment: "Record as Partial Payment (Customer Debt)",
    amount_paid_rwf: "Amount Paid (RWF)",
    remaining: "Remaining",
    sale_recorded: "Sale Recorded!",
    new_sale_btn: "New Sale",
    print_receipt: "Print Receipt",

    // SalesList
    receipt_no: "Receipt No",
    branch: "Branch",
    showing: "Showing",
    of: "of",
    previous: "Previous",
    next: "Next",
    voided: "Voided",

    // StockList
    stock_page_title: "Stock",
    stock_subtitle: "Manage your product inventory",
    add_product: "Add Product",
    edit_product: "Edit Product",
    total_items: "Total Items",
    product: "Product",
    barcode_col: "Barcode",
    qty: "Qty",
    cost: "Cost",
    sell: "Sell",
    search_products: "Search products…",
    all_categories: "All Categories",
    all_status: "All Status",
    no_products_yet: "No products yet",
    product_name_en: "Product Name (English)",
    product_name_rw: "Izina mu Kinyarwanda (optional)",
    unit_of_measure: "Unit of Measure",
    low_stock_alert_at: "Low Stock Alert at",
    cost_price_rwf: "Cost Price (RWF)",
    selling_price_rwf: "Selling Price (RWF)",
    page_of: "Page",
    prev: "Prev",

    // CustomersList
    location: "Location",
    type: "Type",
    segment: "Segment",
    orders: "Orders",
    total_spent: "Total Spent",
    last_purchase: "Last Purchase",
    all_types: "All Types",
    retailer: "Retailer",
    wholesaler: "Wholesaler",
    notes: "Notes",
    vip: "VIP",
    regular: "Regular",
    new_label: "New",
    no_phone: "No phone",

    // Receivables
    accounts_receivable: "Accounts Receivable",
    track_customer_owe: "Track what customers owe you",
    add_receivable: "Add Receivable",
    total_outstanding: "Total Outstanding",
    due_in_7_days: "Due in 7 Days",
    records: "records",
    new_receivable: "New Receivable",
    select_customer: "Select customer...",
    amount_rwf: "Amount (RWF)",
    optional_label: "Optional…",
    create: "Create",
    all_records: "All Records",
    aged_analysis: "Aged Analysis",
    search_customer: "Search customer…",
    no_receivables_yet: "No receivables yet",
    no_receivables_desc: "Add a receivable to start tracking customer debts",
    no_due_date: "No due date",
    due_prefix: "Due",
    aged_receivables: "Aged Receivables Analysis",
    no_outstanding: "No outstanding receivables",
    pay: "Pay",

    // Payables
    accounts_payable: "Accounts Payable",
    track_supplier_owe: "Track money you owe to suppliers",
    add_payable: "Add Payable",
    total_we_owe: "Total We Owe",
    new_payable: "New Payable",
    supplier_optional: "Supplier (optional)",
    select_supplier: "Select supplier…",
    what_debt_for: "What is this debt for?",
    no_payables_yet: "No payables yet",
    no_payables_desc: "Record debts you owe to suppliers",
    search_supplier_note: "Search supplier or note…",
    no_supplier: "No supplier",

    // PurchaseOrders
    track_stock_orders: "Track stock orders from suppliers",
    new_order: "New Order",
    new_purchase_order: "New Purchase Order",
    supplier_label: "Supplier",
    order_date: "Order Date",
    expected_arrival: "Expected Arrival",
    optional_notes: "Optional notes...",
    cancel_btn: "Cancel",
    create_order: "Create Order",
    loading_orders: "Loading orders...",
    no_orders_yet: "No purchase orders yet",
    no_orders_desc: "Create an order to start tracking stock from suppliers",
    advance: "Advance",
    expected_prefix: "Expected",
    procurement_costs: "Procurement Costs",

    // SuppliersList
    suppliers_subtitle: "China supplier contacts",
    add_supplier: "Add Supplier",
    edit_supplier: "Edit Supplier",
    supplier_col: "Supplier",
    city_country: "City / Country",
    specialty: "Specialty",
    wechat: "WeChat",
    orders_count: "Orders",
    total_invested: "Total Invested",
    reliability: "Reliability",
    no_suppliers_found: "No suppliers found",
    supplier_name: "Supplier Name",
    wechat_id: "WeChat ID",
    whatsapp: "WhatsApp",
    country: "Country",
    delete_supplier_confirm: "Delete this supplier?",

    // ProfitLoss
    daily_breakdown: "Daily Breakdown",
    daily_pnl_subtitle: "Daily P&L Performance",
    monthly_linked_activity: "Monthly Linked Business Activity",
    summary_linked: "Summary of linked transactions for",
    month_col: "Month",
    cogs_stock_cost: "COGS (Stock Cost)",
    procurements: "Procurements",
    net_profit_col: "Net Profit",
    linked_activity_metrics: "Linked Activity Metrics",
    daily_pnl_trend: "Daily Profit & Loss Trend",
    everyday_pnl: "Everyday Profit & Loss Statement",
    daily_performance_for: "Daily performance for",
    no_activity: "No activity",
    sales_count_label: "Sales",
    cust_label: "Cust",
    proc_label: "Proc",
    supp_label: "Supp",
  },

  rw: {
    // Nav Sections
    main_menu: "Menu Nyamukuru",
    management: "Icungamutungo",
    finance: "Imali",
    reports: "Raporo",
    others: "Ibindi",
    production_nav: "Umusaruro",
    production: "Umusaruro",
    real_estate: "Inyubako n'Ubutaka",
    supply_chain: "Ihererekanya ry'Ibicuruzwa",
    operations: "Imikorere",

    // Nav Items
    dashboard: "Incamake",
    stock: "SITOKE",
    sales: "Ubucuruzi",
    retail_sales: "Kugurisha Buri Munsi",
    wholesale_orders: "Amaguru Manini",
    procurement: "Kugura Ibicuruzwa",
    workers: "Abakozi",
    customers: "Abakiriya",
    suppliers: "Abaranguza",
    invoices: "Inyemezabwishyu",
    expenses: "Amafaranga Akoreshejwe",
    profit_loss: "Inyungu n'Igihombo",
    financial_books: "Ibitabo by'Imari",
    financial_books_sub: "Ikawa, ledger, cashbook na balance sheet bivuka ako kanya",
    sales_report: "Raporo y'Ubucuruzi",
    stock_report: "Raporo y'Ububiko",
    worker_performance: "Imikorere y'Abakozi",
    audit_log: "Urutonde rw'Ibikorwa",
    notifications: "Imenyesha",
    settings: "Igenamiterere",
    raw_materials: "Ibikoresho by'Ibanze",
    finished_goods: "Ibyarangiye Gukorwa",
    production_runs: "Inzira y'Umusaruro",
    properties: "Inyubako",
    tenants: "Abapangiye",
    rent_payments: "Ubukode",
    maintenance: "Gusana no Kubungabunga",
    debt_management: "Icungamwenda",
    receivables: "Amadeni Tweberewe",
    due_date: "Itariki Ntarengwa",
    debtor: "Uwufitiye Umwenda",
    creditor: "Uwuhererewe",
    pay_debt: "Emeza Kwishyura",
    add_debt: "Andika Umwenda",
    total_debt: "Imyenda Yose Hamwe",
    overdue: "Yarenze Igihe",

    // Businesses
    industry: "INZIRA INSIGHTS",
    shop: "INZIRA INSIGHTS",
    real_estate_biz: "INZIRA INSIGHTS",
    switch_business: "Hindura Ubucuruzi",

    // Auth
    welcome_back: "Murakaza Neza",
    sign_in_account: "Injira muri Konti Yawe",
    email: "Imeyili",
    password: "Ijambo Ryibanga",
    remember_me: "Nyibuka",
    sign_in: "Injira",
    signing_in: "Biracyinjira...",
    login_failed: "Kwinjira ntibyakunze. Reba imeyili cyangwa ijambo ryibanga.",

    // General Actions
    save: "Bika",
    cancel: "Reka",
    delete: "Siba",
    edit: "Hindura",
    add: "Ongeraho",
    search: "Shaka",
    loading: "Biratunganywa...",
    actions: "Ibikorwa",
    view: "Reba",
    print: "Sohora ku Mpapuro",
    export: "Bika nk'Inyandiko",
    filter: "Hitamo",
    clear: "Kuraho",
    all: "Byose",
    status: "Imiterere",
    date: "Itariki",
    total: "Imirimo Yose",
    amount: "Amafaranga",
    name: "Izina",
    phone: "Telefone",
    category: "Icyiciro",
    description: "Ibisobanuro",
    success: "Byagenze Neza",
    error: "Habaye Ikosa",
    confirm_delete: "Uremeza ko ushaka gusiba ibi?",

    // Dashboard
    total_revenue: "Amafaranga Yose Yinjiye",
    total_sales: "Ubucuruzi Bwose",
    stock_value: "Agaciro k'Ububiko",
    active_workers: "Abakozi Bari mu Kazi",
    recent_activity: "Ibiherutse Gukorwa",
    top_selling_items: "Ibicuruzwa Bikunzwe Cyane",
    sales_trend: "Imishinga y'Ubucuruzi",
    low_stock_alerts: "Impuruza z'Ububiko Buke",
    items_sold: "byagurishijwe",

    // Stock & Production
    add_item: "Ongeraho Igicuruzwa",
    item_name: "Izina ry'Igicuruzwa",
    barcode: "Kode ya Barkode",
    quantity: "Umubare",
    cost_price: "Ikiguzi cyo Kugura",
    selling_price: "Igiciro cyo Kugurisha",
    min_stock: "Umubare w'Ntarengwa",
    size: "Ingano",
    color: "Ibara",
    in_stock: "Bihari mu Bubiko",
    low_stock: "Birimo Gushira",
    out_of_stock: "Byarangiye",
    transfer_stock: "Imura Ibicuruzwa",
    planned: "Byateganyijwe",
    in_progress: "Biracyakorwa",
    completed: "Byarangiye",
    cancelled: "Byahagaritswe",

    // Sales & Rent
    new_sale: "Gutangira Kugurisha",
    invoice_no: "Nomero y'Inyemezabwishyu",
    customer: "Umukiriya",
    payment_method: "Uburyo bwo Kwishyura",
    subtotal: "Iteranyirizo Rito",
    tax: "Umusoro",
    grand_total: "Amafaranga Yose",
    void_sale: "Kuraho Kugurisha",
    sale_details: "Ibisobanuro by'Ubucuruzi",
    cash: "Amafaranga y'Intoki",
    momo: "Momo ya Telefone",
    bank: "Banki",

    // Real Estate
    occupied: "Irimo Abatuye",
    vacant: "Nta Mutuye",
    partial: "Yuzuyemo Igice",
    address: "Aho Iherereye",
    address_label: "Aho Riherereye",
    rent_status: "Imiterere y'Ubukode",
    paid: "Yishyuwe",
    pending: "Itegerejwe",

    // Finance
    revenue: "Amafaranga Yinjiye",
    cogs: "Ikiguzi cy'Ibicuruzwa Byagurishijwe",
    gross_profit: "Inyungu Mbumbe",
    net_profit: "Inyungu Nyayo",
    operating_expenses: "Amafaranga Akoreshwa mu Bucuruzi",
    monthly_summary: "Incamake y'Ukwezi",

    // Settings
    business_info: "Amakuru y'Ubucuruzi",
    shop_name: "Izina ry'Iduka",
    city: "Umujyi",
    currency: "Ifaranga Rikoreshwa",
    language: "Ururimi",
    roles_permissions: "Inshingano n'Uburenganzira",

    // Nav sections
    nav_main: "Nyamukuru",
    nav_inventory: "Ububiko",
    nav_crm: "Abakiriya",
    nav_finance: "Imali",
    nav_reports: "Raporo",
    nav_intelligence: "Ubushakashatsi",
    nav_admin: "Ubuyobozi",
    nav_lender: "Inguzanyo",

    // Nav items (missing)
    point_of_sale: "IBYO DUFITE",
    sales_history: "IBYO TWAKOZE",
    purchase_orders: "Amaguru",
    payables: "Amadeni Dufitiye",
    tax_reports: "Raporo y'Imisoro",
    health_score: "Amanota y'Ubucuruzi",
    pulse_admin: "Ubuyobozi Bukuru",
    portfolio: "Urutonde rw'Inguzanyo",

    // Dashboard strings
    dashboard_subtitle: "Incamake y'ubucuruzi bwawe uyu munsi",
    revenue_today: "Amafaranga Yinjiye Uyu Munsi",
    net_cash_today: "Amafaranga Asigaye Uyu Munsi",
    monthly_revenue: "Amafaranga y'Ukwezi",
    monthly_profit: "Inyungu y'Ukwezi",
    business_health_score: "Amanota y'Ubuzima bw'Ubucuruzi",
    health_score_subtitle: "Abarwa hashingiwe ku makuru yawe",
    sales_trend_7day: "Imishinga y'Ubucuruzi — Iminsi 7",
    no_sales_data: "Nta makuru y'ubucuruzi — Tangira kugurisha kugira ngo ubone imishinga",
    all_stock_ok: "✓ Ububiko bwose buhari",
    get_advisory_help: "Bona inama z'inzobere",
    no_score_yet: "Nta manota nawe — Ongeraho ubucuruzi n'amafaranga akoreshejwe",
    add_expense: "Ongeraho Amafaranga Akoreshejwe",
    receive_stock: "Injiza Ibicuruzwa",
    transactions: "ibyakozwe",
    items_need_attention: "ibicuruzwa bisaba amaguru",
    view_all_stock: "Reba ububiko bwose →",
    no_recent_activity: "Nta cyo cyabaye vuba",
    sales_minus_expenses: "Ubucuruzi buvanye n'amafaranga akoreshejwe",
    revenue_minus_cogs: "Amafaranga avanye n'ikiguzi n'amafaranga akoreshejwe",
    vs_last_month: "ugereranije n'ukwezi gushize",
    out_of_100: "kuri 100",

    // NewSale
    point_of_sale_subtitle: "Andika kugurisha gushya",
    search_by_name_or_barcode: "Shakisha izina cyangwa kode…",
    current_sale: "Kugurisha Bikorwa",
    cart_empty: "Nta kintu mu gasanduku",
    customer_name_optional: "Izina ry'umukiriya (ntibisabwa)",
    complete_sale: "Soza Kugurisha",
    no_products_match: "Nta bicuruzwa bihuye n'ubushakashatsi",
    out_label: "BYASHIZE",
    left_in_stock: "bisigaye",
    confirm_sale: "Emeza Kugurisha",
    walk_in: "Uwasuye",
    payment_label: "Kwishyura",
    record_sale: "Andika Kugurisha",
    partial_payment: "Andika nk'Ubwishyu bw'Igice (Umwenda w'Umukiriya)",
    amount_paid_rwf: "Amafaranga Yishyuwe (RWF)",
    remaining: "Asigaye",
    sale_recorded: "Kugurisha Kwanditswe!",
    new_sale_btn: "Gutangira Kugurisha Gushya",
    print_receipt: "Sohora Inyemezabuguzi",

    // SalesList
    receipt_no: "Nomero y'Inyemezabuguzi",
    branch: "Ishami",
    showing: "Kwerekana",
    of: "kuri",
    previous: "Inyuma",
    next: "Imbere",
    voided: "Irasiwe",

    // StockList
    stock_page_title: "Ububiko",
    stock_subtitle: "Gucunga ububiko bw'ibicuruzwa",
    add_product: "Ongeraho Igicuruzwa",
    edit_product: "Hindura Igicuruzwa",
    total_items: "Ibicuruzwa Byose",
    product: "Igicuruzwa",
    barcode_col: "Kode ya Barkode",
    qty: "Umubare",
    cost: "Ikiguzi",
    sell: "Igiciro",
    search_products: "Shakisha ibicuruzwa…",
    all_categories: "Ibyiciro Byose",
    all_status: "Imiterere Yose",
    no_products_yet: "Nta bicuruzwa naramwe",
    product_name_en: "Izina ry'Igicuruzwa (Icyongereza)",
    product_name_rw: "Izina mu Kinyarwanda (ntibisabwa)",
    unit_of_measure: "Ingano y'Igipimo",
    low_stock_alert_at: "Impuruza y'Ububiko Buke",
    cost_price_rwf: "Ikiguzi cyo Kugura (RWF)",
    selling_price_rwf: "Igiciro cyo Kugurisha (RWF)",
    page_of: "Urupapuro",
    prev: "Inyuma",

    // CustomersList
    location: "Aho atuye",
    type: "Ubwoko",
    segment: "Icyiciro",
    orders: "Amaguru",
    total_spent: "Yishyuye Yose",
    last_purchase: "Kugura Kwa Nyuma",
    all_types: "Ubwoko Bwose",
    retailer: "Ugura Buke",
    wholesaler: "Ugura Manini",
    notes: "Ibisobanuro Bigereka",
    vip: "VIP",
    regular: "Bisanzwe",
    new_label: "Mushya",
    no_phone: "Nta telefone",

    // Receivables
    accounts_receivable: "Amadeni Tweberewe",
    track_customer_owe: "Kurikirana ibyo abakiriya badufitiiye",
    add_receivable: "Ongeraho Umwenda",
    total_outstanding: "Yose Itarishyuwe",
    due_in_7_days: "Igatengwa mu Minsi 7",
    records: "inyandiko",
    new_receivable: "Umwenda Mushya",
    select_customer: "Hitamo umukiriya...",
    amount_rwf: "Amafaranga (RWF)",
    optional_label: "Ntibisabwa…",
    create: "Shiraho",
    all_records: "Inyandiko Zose",
    aged_analysis: "Isesengura ry'Igihe",
    search_customer: "Shakisha umukiriya…",
    no_receivables_yet: "Nta madeni naramwe",
    no_receivables_desc: "Ongeraho umwenda kugira ngo utangire kurikirana amadeni y'abakiriya",
    no_due_date: "Nta tariki ntarengwa",
    due_prefix: "Igatengwa",
    aged_receivables: "Isesengura ry'Amadeni Hashingiwe ku Gihe",
    no_outstanding: "Nta madeni asigaye",
    pay: "Ishyura",

    // Payables
    accounts_payable: "Amadeni Dufitiye Abandi",
    track_supplier_owe: "Kurikirana ibyo dufitiye abaranguza",
    add_payable: "Ongeraho Umwenda",
    total_we_owe: "Yose Twowe",
    new_payable: "Umwenda Mushya",
    supplier_optional: "Umuranguzabikorwa (ntibisabwa)",
    select_supplier: "Hitamo umuranguzabikorwa…",
    what_debt_for: "Umwenda uwo ni uwuhe?",
    no_payables_yet: "Nta madeni naramwe",
    no_payables_desc: "Andika amadeni ufitiye abaranguza",
    search_supplier_note: "Shakisha umuranguzabikorwa cyangwa inyandiko…",
    no_supplier: "Nta muranguzabikorwa",

    // PurchaseOrders
    track_stock_orders: "Kurikirana amaguru y'ibicuruzwa kuva ku baranguza",
    new_order: "Itegeko Rishya",
    new_purchase_order: "Itegeko Rishya ryo Kugura",
    supplier_label: "Umuranguzabikorwa",
    order_date: "Itariki y'Itegeko",
    expected_arrival: "Itariki Iteganywa yo Kugeraho",
    optional_notes: "Ibisobanuro bigereka...",
    cancel_btn: "Reka",
    create_order: "Shiraho Itegeko",
    loading_orders: "Amaguru aratunganywa...",
    no_orders_yet: "Nta maguru naramwe",
    no_orders_desc: "Shiraho itegeko kugira ngo utangire kurikirana ibicuruzwa biva ku baranguza",
    advance: "Ongera Intambwe",
    expected_prefix: "Biteganyijwe",
    procurement_costs: "Amafaranga yo Kugura",

    // SuppliersList
    suppliers_subtitle: "Abaranguza bo mu Bushinwa",
    add_supplier: "Ongeraho Umuranguzabikorwa",
    edit_supplier: "Hindura Umuranguzabikorwa",
    supplier_col: "Umuranguzabikorwa",
    city_country: "Umujyi / Igihugu",
    specialty: "Inzobere",
    wechat: "WeChat",
    orders_count: "Amaguru",
    total_invested: "Yamagariye Yose",
    reliability: "Urwizikirane",
    no_suppliers_found: "Nta baranguza babonetse",
    supplier_name: "Izina ry'Umuranguzabikorwa",
    wechat_id: "Konti ya WeChat",
    whatsapp: "WhatsApp",
    country: "Igihugu",
    delete_supplier_confirm: "Siba uyu muranguzabikorwa?",

    // ProfitLoss
    daily_breakdown: "Itangazo ry'Buri Munsi",
    daily_pnl_subtitle: "Imikorere y'Inyungu n'Igihombo Buri Munsi",
    monthly_linked_activity: "Ibikorwa by'Ubucuruzi Bijyanye n'Ukwezi",
    summary_linked: "Incamake y'ibyakozwe bijyanye muri",
    month_col: "Ukwezi",
    cogs_stock_cost: "Ikiguzi cy'Ibicuruzwa (COGS)",
    procurements: "Amaguru",
    net_profit_col: "Inyungu Nyayo",
    linked_activity_metrics: "Ingano z'Ibikorwa Bijyanye",
    daily_pnl_trend: "Imishinga y'Inyungu n'Igihombo Buri Munsi",
    everyday_pnl: "Incamake y'Inyungu n'Igihombo ya Buri Munsi",
    daily_performance_for: "Imikorere ya buri munsi ya",
    no_activity: "Nta bikorwa",
    sales_count_label: "Ubucuruzi",
    cust_label: "Abakiriya",
    proc_label: "Amaguru",
    supp_label: "Abaranguza",
  },

  fr: {
    // Nav Sections
    main_menu: "Menu Principal",
    management: "Gestion",
    finance: "Finance",
    reports: "Rapports",
    others: "Autres",
    production_nav: "Production",
    production: "Production",
    real_estate: "Immobilier",
    supply_chain: "Chaîne d'Approvisionnement",
    operations: "Opérations",

    // Nav Items
    dashboard: "Tableau de Bord",
    stock: "SITOKE",
    sales: "Ventes",
    retail_sales: "Ventes au Détail",
    wholesale_orders: "Commandes en Gros",
    procurement: "Approvisionnement",
    workers: "Employés",
    customers: "Clients",
    suppliers: "Fournisseurs",
    invoices: "Factures",
    expenses: "Dépenses",
    profit_loss: "Profits & Pertes",
    financial_books: "Livres Comptables",
    financial_books_sub: "Journal, grand livre, livre de caisse & balance de vérification auto-générés",
    sales_report: "Rapport des Ventes",
    stock_report: "Rapport de Stock",
    worker_performance: "Performance des Employés",
    audit_log: "Journal d'Audit",
    notifications: "Notifications",
    settings: "Paramètres",
    raw_materials: "Matières Premières",
    finished_goods: "Produits Finis",
    production_runs: "Cycles de Production",
    properties: "Propriétés",
    tenants: "Locataires",
    rent_payments: "Paiements de Loyer",
    maintenance: "Maintenance",
    debt_management: "Gestion des Dettes",
    receivables: "Créances",
    due_date: "Date d'Échéance",
    debtor: "Débiteur",
    creditor: "Créancier",
    pay_debt: "Enregistrer un Paiement",
    add_debt: "Ajouter une Dette",
    total_debt: "Total des Dettes",
    overdue: "En Retard",

    // Businesses
    industry: "INZIRA INSIGHTS",
    shop: "INZIRA INSIGHTS",
    real_estate_biz: "INZIRA INSIGHTS",
    switch_business: "Changer d'Entreprise",

    // Auth
    welcome_back: "Bienvenue",
    sign_in_account: "Connectez-vous à votre compte",
    email: "Adresse e-mail",
    password: "Mot de passe",
    remember_me: "Se souvenir de moi",
    sign_in: "Se connecter",
    signing_in: "Connexion en cours...",
    login_failed: "Échec de connexion. Vérifiez vos identifiants.",

    // General Actions
    save: "Enregistrer",
    cancel: "Annuler",
    delete: "Supprimer",
    edit: "Modifier",
    add: "Ajouter",
    search: "Rechercher",
    loading: "Chargement...",
    actions: "Actions",
    view: "Voir",
    print: "Imprimer",
    export: "Exporter",
    filter: "Filtrer",
    clear: "Effacer",
    all: "Tous",
    status: "Statut",
    date: "Date",
    total: "Total",
    amount: "Montant",
    name: "Nom",
    phone: "Téléphone",
    category: "Catégorie",
    description: "Description",
    success: "Succès",
    error: "Erreur",
    confirm_delete: "Êtes-vous sûr de vouloir supprimer ceci ?",

    // Dashboard
    total_revenue: "Revenu Total",
    total_sales: "Ventes Totales",
    stock_value: "Valeur du Stock",
    active_workers: "Employés Actifs",
    recent_activity: "Activité Récente",
    top_selling_items: "Articles les Plus Vendus",
    sales_trend: "Tendance des Ventes",
    low_stock_alerts: "Alertes de Stock Bas",
    items_sold: "articles vendus",

    // Stock & Production
    add_item: "Ajouter un Article",
    item_name: "Nom de l'Article",
    barcode: "Code-barre",
    quantity: "Quantité",
    cost_price: "Prix de Revient",
    selling_price: "Prix de Vente",
    min_stock: "Stock Minimum",
    size: "Taille",
    color: "Couleur",
    in_stock: "En Stock",
    low_stock: "Stock Bas",
    out_of_stock: "Rupture de Stock",
    transfer_stock: "Transférer le Stock",
    planned: "Planifié",
    in_progress: "En Cours",
    completed: "Terminé",
    cancelled: "Annulé",

    // Sales & Rent
    new_sale: "Nouvelle Vente",
    invoice_no: "N° de Facture",
    customer: "Client",
    payment_method: "Mode de Paiement",
    subtotal: "Sous-total",
    tax: "Taxe",
    grand_total: "Total Général",
    void_sale: "Annuler la Vente",
    sale_details: "Détails de la Vente",
    cash: "Espèces",
    momo: "Mobile Money",
    bank: "Virement Bancaire",

    // Real Estate
    occupied: "Occupé",
    vacant: "Vacant",
    partial: "Partiel",
    address: "Adresse",
    address_label: "Adresse",
    rent_status: "Statut du Loyer",
    paid: "Payé",
    pending: "En Attente",

    // Finance
    revenue: "Revenus",
    cogs: "Coût des Marchandises Vendues",
    gross_profit: "Bénéfice Brut",
    net_profit: "Bénéfice Net",
    operating_expenses: "Charges d'Exploitation",
    monthly_summary: "Résumé Mensuel",

    // Settings
    business_info: "Informations de l'Entreprise",
    shop_name: "Nom de la Boutique",
    city: "Ville",
    currency: "Devise",
    language: "Langue",
    roles_permissions: "Rôles & Permissions",

    // Nav sections
    nav_main: "Principal",
    nav_inventory: "Inventaire",
    nav_crm: "Clients",
    nav_finance: "Finance",
    nav_reports: "Rapports",
    nav_intelligence: "Intelligence",
    nav_admin: "Administration",
    nav_lender: "Prêteur",

    // Nav items (missing)
    point_of_sale: "Point de Vente",
    sales_history: "Historique des Ventes",
    purchase_orders: "Bons de Commande",
    payables: "Dettes Fournisseurs",
    tax_reports: "Rapports de Taxes",
    health_score: "Score de Santé",
    pulse_admin: "Administration Pulse",
    portfolio: "Portefeuille",

    // Dashboard strings
    dashboard_subtitle: "Voici un aperçu de votre activité du jour",
    revenue_today: "Revenu du Jour",
    net_cash_today: "Trésorerie Nette du Jour",
    monthly_revenue: "Revenu Mensuel",
    monthly_profit: "Bénéfice Mensuel",
    business_health_score: "Score de Santé de l'Entreprise",
    health_score_subtitle: "Calculé à partir de vos données",
    sales_trend_7day: "Tendance des Ventes — 7 Jours",
    no_sales_data: "Aucune donnée de vente — Effectuez votre première vente pour voir la tendance",
    all_stock_ok: "✓ Tous les niveaux de stock sont OK",
    get_advisory_help: "Obtenir des conseils",
    no_score_yet: "Pas encore de score — Ajoutez des ventes et des dépenses pour être évalué",
    add_expense: "Ajouter une Dépense",
    receive_stock: "Recevoir du Stock",
    transactions: "transactions",
    items_need_attention: "articles nécessitent attention",
    view_all_stock: "Voir tout le stock →",
    no_recent_activity: "Aucune activité récente",
    sales_minus_expenses: "Ventes moins dépenses",
    revenue_minus_cogs: "Revenus moins dépenses et coût des marchandises",
    vs_last_month: "vs mois dernier",
    out_of_100: "sur 100",

    // NewSale
    point_of_sale_subtitle: "Enregistrer une nouvelle vente",
    search_by_name_or_barcode: "Rechercher par nom ou code-barre…",
    current_sale: "Vente en Cours",
    cart_empty: "Le panier est vide",
    customer_name_optional: "Nom du client (optionnel)",
    complete_sale: "Finaliser la Vente",
    no_products_match: "Aucun produit ne correspond à votre recherche",
    out_label: "ÉPUISÉ",
    left_in_stock: "restant",
    confirm_sale: "Confirmer la Vente",
    walk_in: "Client de passage",
    payment_label: "Paiement",
    record_sale: "Enregistrer la Vente",
    partial_payment: "Enregistrer comme Paiement Partiel (Dette Client)",
    amount_paid_rwf: "Montant Payé (RWF)",
    remaining: "Reste",
    sale_recorded: "Vente Enregistrée !",
    new_sale_btn: "Nouvelle Vente",
    print_receipt: "Imprimer le Reçu",

    // SalesList
    receipt_no: "N° de Reçu",
    branch: "Succursale",
    showing: "Affichage",
    of: "sur",
    previous: "Précédent",
    next: "Suivant",
    voided: "Annulé",

    // StockList
    stock_page_title: "Stock",
    stock_subtitle: "Gérer votre inventaire de produits",
    add_product: "Ajouter un Produit",
    edit_product: "Modifier le Produit",
    total_items: "Total des Articles",
    product: "Produit",
    barcode_col: "Code-barre",
    qty: "Qté",
    cost: "Coût",
    sell: "Vente",
    search_products: "Rechercher des produits…",
    all_categories: "Toutes les Catégories",
    all_status: "Tous les Statuts",
    no_products_yet: "Aucun produit pour l'instant",
    product_name_en: "Nom du Produit (Anglais)",
    product_name_rw: "Nom en Kinyarwanda (optionnel)",
    unit_of_measure: "Unité de Mesure",
    low_stock_alert_at: "Alerte Stock Bas à",
    cost_price_rwf: "Prix de Revient (RWF)",
    selling_price_rwf: "Prix de Vente (RWF)",
    page_of: "Page",
    prev: "Préc",

    // CustomersList
    location: "Lieu",
    type: "Type",
    segment: "Segment",
    orders: "Commandes",
    total_spent: "Total Dépensé",
    last_purchase: "Dernier Achat",
    all_types: "Tous les Types",
    retailer: "Détaillant",
    wholesaler: "Grossiste",
    notes: "Notes",
    vip: "VIP",
    regular: "Régulier",
    new_label: "Nouveau",
    no_phone: "Pas de téléphone",

    // Receivables
    accounts_receivable: "Comptes Clients",
    track_customer_owe: "Suivre ce que les clients vous doivent",
    add_receivable: "Ajouter une Créance",
    total_outstanding: "Total Impayé",
    due_in_7_days: "Dû dans 7 Jours",
    records: "enregistrements",
    new_receivable: "Nouvelle Créance",
    select_customer: "Sélectionner un client...",
    amount_rwf: "Montant (RWF)",
    optional_label: "Optionnel…",
    create: "Créer",
    all_records: "Tous les Enregistrements",
    aged_analysis: "Analyse par Ancienneté",
    search_customer: "Rechercher un client…",
    no_receivables_yet: "Aucune créance pour l'instant",
    no_receivables_desc: "Ajoutez une créance pour commencer à suivre les dettes des clients",
    no_due_date: "Pas de date d'échéance",
    due_prefix: "Dû le",
    aged_receivables: "Analyse des Créances par Ancienneté",
    no_outstanding: "Aucune créance en cours",
    pay: "Payer",

    // Payables
    accounts_payable: "Comptes Fournisseurs",
    track_supplier_owe: "Suivre l'argent que vous devez aux fournisseurs",
    add_payable: "Ajouter une Dette",
    total_we_owe: "Total que Nous Devons",
    new_payable: "Nouvelle Dette",
    supplier_optional: "Fournisseur (optionnel)",
    select_supplier: "Sélectionner un fournisseur…",
    what_debt_for: "À quoi correspond cette dette ?",
    no_payables_yet: "Aucune dette pour l'instant",
    no_payables_desc: "Enregistrez les dettes envers vos fournisseurs",
    search_supplier_note: "Rechercher fournisseur ou note…",
    no_supplier: "Pas de fournisseur",

    // PurchaseOrders
    track_stock_orders: "Suivre les commandes de stock auprès des fournisseurs",
    new_order: "Nouvelle Commande",
    new_purchase_order: "Nouveau Bon de Commande",
    supplier_label: "Fournisseur",
    order_date: "Date de Commande",
    expected_arrival: "Arrivée Prévue",
    optional_notes: "Notes optionnelles...",
    cancel_btn: "Annuler",
    create_order: "Créer la Commande",
    loading_orders: "Chargement des commandes...",
    no_orders_yet: "Aucun bon de commande pour l'instant",
    no_orders_desc: "Créez une commande pour commencer à suivre le stock des fournisseurs",
    advance: "Avancer",
    expected_prefix: "Prévu le",
    procurement_costs: "Coûts d'Approvisionnement",

    // SuppliersList
    suppliers_subtitle: "Contacts fournisseurs Chine",
    add_supplier: "Ajouter un Fournisseur",
    edit_supplier: "Modifier le Fournisseur",
    supplier_col: "Fournisseur",
    city_country: "Ville / Pays",
    specialty: "Spécialité",
    wechat: "WeChat",
    orders_count: "Commandes",
    total_invested: "Total Investi",
    reliability: "Fiabilité",
    no_suppliers_found: "Aucun fournisseur trouvé",
    supplier_name: "Nom du Fournisseur",
    wechat_id: "ID WeChat",
    whatsapp: "WhatsApp",
    country: "Pays",
    delete_supplier_confirm: "Supprimer ce fournisseur ?",

    // ProfitLoss
    daily_breakdown: "Détail Quotidien",
    daily_pnl_subtitle: "Performance P&L Quotidienne",
    monthly_linked_activity: "Activité Commerciale Mensuelle Liée",
    summary_linked: "Résumé des transactions liées pour",
    month_col: "Mois",
    cogs_stock_cost: "CMV (Coût du Stock)",
    procurements: "Approvisionnements",
    net_profit_col: "Bénéfice Net",
    linked_activity_metrics: "Métriques d'Activité Liée",
    daily_pnl_trend: "Tendance P&L Quotidienne",
    everyday_pnl: "État des Profits & Pertes Quotidiens",
    daily_performance_for: "Performance quotidienne pour",
    no_activity: "Aucune activité",
    sales_count_label: "Ventes",
    cust_label: "Clients",
    proc_label: "Appro",
    supp_label: "Fourn",
  },
};

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(localStorage.getItem("inzira_lang") || "en");

  const t = useCallback((key) => {
    return TRANSLATIONS[lang]?.[key] || TRANSLATIONS["en"][key] || key;
  }, [lang]);

  const switchLanguage = (newLang) => {
    setLang(newLang);
    localStorage.setItem("inzira_lang", newLang);
  };

  const cycleLanguage = () => {
    const idx = LANGUAGES.findIndex(l => l.code === lang);
    const next = LANGUAGES[(idx + 1) % LANGUAGES.length];
    switchLanguage(next.code);
  };

  const currentLang = LANGUAGES.find(l => l.code === lang) || LANGUAGES[0];

  return (
    <LanguageContext.Provider value={{ lang, t, switchLanguage, cycleLanguage, currentLang, LANGUAGES }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLanguage must be used within LanguageProvider");
  return ctx;
}
